apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: golang-app-ms
        image: go-app-ms:v5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80