apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: golang-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32730
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  type: NodePort