version: "3.9"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: go-app-ms:v5
    ports:
      - "8000:80"
    restart: always
    networks:
      - web

networks:
  web: